# Import Numpy

In [1]:
import numpy as np

# Check Numpy Version

In [2]:
print('Numpy version: ' + np.__version__)

Numpy version: 1.15.0


# 1. Create Arrays

### create an array from an iterable

In [ ]:
arr = np.array(range(10))
print(arr)

arr = np.array([1,2,3,4,5])
print(arr)

### create an array in a specified data type

In [81]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


### create an aray of evenly spaced values within a specified interval

In [4]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### create an array of evenly spaced numbers in a specified interval

In [5]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(0, 10, 20)
print(arr)

# exclude endpoint and return setp size
arr, step = np.linspace(0, 10, 20, endpoint=False, retstep=True)
print(arr)
print(step)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
0.5


### create an array of random values in a given shape

In [6]:
arr = np.random.rand(3, 3)
print(arr)

[[0.49092008 0.75327598 0.70793096]
 [0.9678623  0.48079467 0.04504932]
 [0.2167024  0.35205732 0.5833361 ]]


### create an array of zeros in a given shape 

In [84]:
zeros = np.zeros((2,3), dtype='i4')
print(zeros)

[[0 0 0]
 [0 0 0]]


### create an array of zeros with the same shape and data type as a given array

In [ ]:
zeros = np.zeros_like(arr)
print(zeros)

### create an array of ones in a given shape 

In [82]:
ones = np.ones((2,3), dtype=np.int32)
print(ones)

[[1 1 1]
 [1 1 1]]


### create an array of ones with the same shape and data type as a given array

In [83]:
ones = np.ones_like(arr, dtype=np.int16)
print(ones)

[[1 1 1]
 [1 1 1]]


### create an array of arbitrary values in a given shape 

In [85]:
empty = np.empty((2,3))
print(empty)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


### create an array of arbitrary values with the same shape and data type as a given array

In [86]:
empty = np.empty_like(arr)
print(empty)

[[0 0 3]
 [0 3 0]]


### create an array of constant values in a given shape  

In [ ]:
p = np.full((2,3), 5, dtype=np.int32)
print(p)

### create an array of constant values with the same shape and data type as a given array

In [87]:
p = np.full_like(arr, 5)
print(p)

[[5 5 5]
 [5 5 5]]


### create an identity matrix with a given diagonal size

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

In [11]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### create an identity matrix with a diagonal offset

In [12]:
identity_matrix = np.eye(5, k=1)    # positive number means upper offset by the number
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
identity_matrix = np.eye(5, k=-2)   # negative number means lower offset by the number
print(identity_matrix)

# 2. Inspect Arrays

In [13]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

### inspect general information of an array

In [14]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x220a1b66200
byteorder:  little
byteswap:  False
type: int64
None


### inspect the data type of an array

In [15]:
print(arr.dtype)

int64


### inspect the dimension of an array

In [16]:
print(arr.shape)

(2, 3)


### inspect length of an array

In [17]:
print(len(arr))

2


### inspect the number of dimensions of an array

In [88]:
print(arr.ndim)

2


### inspect the number of elements in an array

In [89]:
print(arr.size)

6


### inspect the number of bytes of each element in an array

In [20]:
print(arr.itemsize)

8


# 3. Numpy Data Types

### A list of Numpy Data Types

In [90]:
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

### convert data type

In [23]:
arr1 = arr.astype('i8')  
print(arr1.dtype)

int64
float32


In [91]:
arr2 = arr.astype(np.float32)
print(arr2.dtype)

float32


### string data type

In [94]:
# set the max length of the string using S + length, such as 'S10'
# any string longer than the max length will be truncated
s = np.array(['abc', 'defg'], dtype='S10')

In [95]:
# 'np.string_' will set the length of the longest string in the array as the max length 
s = np.array([1.96,2.0,8], dtype=np.string_)
print(s.dtype)

|S4


# 4. Sampling Methods

### set seed

In [96]:
np.random.seed(123)

### set random state which is separate from the global seed

In [169]:
rs = np.random.RandomState(321)
rs.rand(10)

array([0.88594794, 0.07791236, 0.97964616, 0.24767146, 0.75288472,
       0.52667564, 0.90755375, 0.8840703 , 0.08926896, 0.5173446 ])

### generate a random sample from interval [0, 1) in a given shape

In [98]:
# generate a random scalar
print(np.random.rand())      

0.6964691855978616


In [99]:
# generate a 1-D array
print(np.random.rand(3,))           

[0.28613933 0.22685145 0.55131477]


In [100]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


### generate a sample from the standard normal distribution (with mean equal to o and variance 1)

In [27]:
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


### generate an array of random integers in a given interval [low, high)

In [101]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 3, 'i8'))

[5 1 1]


### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [102]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.73799541 0.18249173 0.17545176 0.53155137 0.53182759 0.63440096
 0.84943179 0.72445532 0.61102351 0.72244338]
[0.32295891 0.36178866 0.22826323 0.29371405 0.63097612 0.09210494
 0.43370117 0.43086276 0.4936851  0.42583029]
[0.31226122 0.42635131 0.89338916 0.94416002 0.50183668 0.62395295
 0.1156184  0.31728548 0.41482621 0.86630916]
[0.25045537 0.48303426 0.98555979 0.51948512 0.61289453 0.12062867
 0.8263408  0.60306013 0.54506801 0.34276383]


### # generate a random sample in a given 1-D array

In [105]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.1, 0.8, 0.1]))

[1 1 1 0 1 1 1 1 1 1]


In [103]:
print(np.random.choice(3, 10))

[0 1 2 1 1 1 2 0 2 2]


In [104]:
print(np.random.choice([1,2,3], 10))

[2 3 3 2 3 1 3 3 2 2]


### shuffle the array in place

In [31]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[1 2 8 5 4 0 6 7 9 3]


In [ ]:
np.random.shuffle(arr)
print(arr)

### generate a permutation of an array

In [108]:
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [9 0 2 5 7 3 8 6 4 1]


# 5. Mathematical Functions

In [109]:
arr = np.random.rand(5,5)

### element-wise addition, subtraction, multiplication and division

In [110]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.00413464 10.63802252 10.05764801 10.04302691 10.87505113]
 [10.2925876  10.76276766 10.36786526 10.87350227 10.02942373]
 [10.55204372 10.2402475  10.88480501 10.46023842 10.19317033]
 [10.2936925  10.81792751 10.55948738 10.67792545 10.80912668]
 [10.86857215 10.41799246 10.05893816 10.478459   10.52115943]]
[[-9.99586536 -9.36197748 -9.94235199 -9.95697309 -9.12494887]
 [-9.7074124  -9.23723234 -9.63213474 -9.12649773 -9.97057627]
 [-9.44795628 -9.7597525  -9.11519499 -9.53976158 -9.80682967]
 [-9.7063075  -9.18207249 -9.44051262 -9.32207455 -9.19087332]
 [-9.13142785 -9.58200754 -9.94106184 -9.521541   -9.47884057]]
[[0.04134643 6.38022518 0.57648015 0.43026907 8.75051134]
 [2.92587604 7.62767659 3.6786526  8.73502266 0.29423734]
 [5.52043722 2.40247504 8.84805011 4.60238424 1.9317033 ]
 [2.93692504 8.17927508 5.59487376 6.77925447 8.09126678]
 [8.68572154 4.17992456 0.58938156 4.78459005 5.2115943 ]]
[[0.00041346 0.06380225 0.0057648  0.00430269 0.08750511]
 [0.02925876 0.0762

### element-wise exponentiation

In [35]:
print(np.exp(arr))

[[2.39528511 1.02986089 1.73679893 1.27156383 2.42251198]
 [1.58445171 1.2130894  1.34137137 2.26579912 1.74977529]
 [1.96978706 2.2459457  2.38350515 1.51890922 1.06070964]
 [1.61358596 1.68397897 1.7871676  1.36233345 2.50899588]
 [1.92581163 1.41799143 1.71788528 1.56682832 1.32620431]]


### element-wise logorithm

In [111]:
# natural log
print(np.log(arr))      

[[-5.48835435 -0.4493817  -2.85339947 -3.14592962 -0.13347295]
 [-1.22899116 -0.2708018  -1.00003855 -0.13524456 -3.52595367]
 [-0.59412803 -1.42608562 -0.12238798 -0.77601061 -1.64418294]
 [-1.22522197 -0.20098157 -0.58073432 -0.38871796 -0.21179979]
 [-0.14090462 -0.87229189 -2.83126659 -0.73718475 -0.65169928]]


In [112]:
# base 2
print(np.log2(arr))     

[[-7.9180216  -0.64832075 -4.11658526 -4.53861706 -0.19256077]
 [-1.77305945 -0.39068442 -1.44275066 -0.19511665 -5.08687587]
 [-0.85714556 -2.05740665 -0.17656854 -1.11954666 -2.37205457]
 [-1.76762165 -0.28995511 -0.83782252 -0.56080147 -0.3055625 ]
 [-0.20328239 -1.25845119 -4.08465428 -1.06353278 -0.94020332]]


In [113]:
# base 10
print(np.log10(arr))    

[[-2.38356201 -0.19516399 -1.23921564 -1.36625987 -0.05796657]
 [-0.53374408 -0.11760773 -0.43431122 -0.05873596 -1.53130222]
 [-0.25802652 -0.61934112 -0.05315243 -0.33701713 -0.71405958]
 [-0.53210714 -0.08728519 -0.25220971 -0.16881806 -0.09198348]
 [-0.0611941  -0.37883156 -1.22960346 -0.32015527 -0.2830294 ]]


### element-wise square root

In [37]:
print(np.sqrt(arr))

[[0.93461343 0.17153348 0.74299645 0.49015049 0.94064075]
 [0.67840874 0.43951147 0.54193404 0.90439345 0.74798889]
 [0.82336228 0.89951469 0.93197219 0.64652336 0.24277182]
 [0.69170731 0.72191373 0.76199214 0.55605665 0.95910512]
 [0.80953536 0.59096648 0.73559095 0.67011446 0.53133884]]


### element-wise sine and cosine

In [38]:
print(np.sin(arr))
print(np.cos(arr))

[[0.7665826  0.02941949 0.52442846 0.23794303 0.77379149]
 [0.44416174 0.19197122 0.28948859 0.72973036 0.5307518 ]
 [0.62717856 0.72368474 0.76340745 0.40592657 0.05890404]
 [0.46041177 0.49788598 0.54855249 0.30429572 0.79553051]
 [0.60943479 0.34218509 0.51507406 0.43411297 0.27858547]]
[[0.64214571 0.99956715 0.85145452 0.97127911 0.63344039]
 [0.89594662 0.98140056 0.95718147 0.68373503 0.8475273 ]
 [0.77887551 0.69013071 0.64591723 0.9139057  0.99826365]
 [0.88770547 0.8672425  0.83611612 0.95257762 0.60591354]
 [0.7928362  0.93963257 0.85714568 0.90085844 0.96041144]]


### sum along a specified axis

In [40]:
# sum along the row
print(np.sum(arr, axis=0))    

[3.14547265 1.90212156 2.83603444 2.23441986 2.70543413]
[2.58002224 2.32451614 2.83255489 2.80933208 2.27705729]


In [114]:
# sum along the column
print(np.sum(arr, axis=1))    

[1.61788322 2.32614652 2.33050499 3.15815951 2.3451212 ]


### compute the min and max along a specified axis

In [115]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.00413464 0.2402475  0.05764801 0.04302691 0.02942373]


In [116]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.87505113 0.87350227 0.88480501 0.81792751 0.86857215]


### compute element-wise min and max of two arrays

In [42]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [117]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.8063202  0.09198998 0.19882625 0.55347503 0.49241385 0.41094045
 0.49053396 0.82320961 0.95876525 0.63480983]
integral:  [5. 3. 9. 6. 3. 5. 4. 2. 2. 5.]


### compute the mean

In [118]:
# compute the overall mean
print(np.mean(arr))

0.4711126177661572


In [ ]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

In [ ]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

### compute the median

In [119]:
# compute the overall median
print(np.median(arr))

0.4784590047029411


In [ ]:
# compute the median along the row
print(np.median(arr, axis=0)) 

In [44]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.62909453 0.38042431 0.56720689 0.44688397 0.54108683]
[0.51600445 0.46490323 0.56651098 0.56186642 0.45541146]
[0.6553475  0.34924138 0.55204372 0.41799246 0.55948738]
[0.55204372 0.46023842 0.67792545 0.52115943 0.4490534 ]


### compute the standard deviation & variance

In [121]:
# compute the overall standard deviation
print(np.std(arr))

[0.36179268 0.31126429 0.24828795 0.19378411 0.25815517]


In [ ]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

In [122]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.36179268 0.31126429 0.24828795 0.19378411 0.25815517]


In [123]:
# compute the overall variance
print(np.var(arr))

0.08824401505335278


In [ ]:
# compute the variance along the row
print(np.var(arr, axis=0))

In [ ]:
# compute the variance along the column
print(np.var(arr, axis=1))

### compute cumulative sum & product

In [ ]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

In [ ]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

In [ ]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

In [124]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[4.13464275e-03 2.63799518e-03 1.52075185e-04 6.54332485e-06
  5.72574384e-06]
 [2.92587604e-01 2.23176362e-01 8.20988302e-02 7.17135142e-02
  2.11007933e-03]
 [5.52043722e-01 1.32627126e-01 1.17349146e-01 5.40085860e-02
  1.04328564e-02]
 [2.93692504e-01 2.40219178e-01 1.34399597e-01 9.11129071e-02
  7.37218838e-02]
 [8.68572154e-01 3.63056608e-01 2.13978869e-02 1.02380117e-02
  5.33563632e-03]]


### element-wise comparison

In [47]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

[False False  True False False]
[ True  True False False False]


In [ ]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

# 6. Slicing & Indexing

In [48]:
arr = np.array(range(100)).reshape((10,10))

### select an element by row and column indices

In [49]:
print(arr[5][5])
# or 
print(arr[5,5])

55
55


### indexing with slicing

In [50]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [ ]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# equivalent to arr[0,:,:,:]
print(arr[0, ...])    

### assign a scalar to a slice by broadcasting

In [51]:
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print(arr)

[[  0   1   2   3   4   5   6   7 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100 100]
 [ 30  31  32  33  34  35  36  37 100 100]
 [ 40  41  42  43  44  45  46  47 100 100]
 [ 50  51  52  53  54  55  56  57 100 100]
 [ 60  61  62  63  64  65  66  67 100 100]
 [ 70  71  72  73  74  75  76  77 100 100]
 [ 80  81  82  83  84  85  86  87 100 100]
 [ 90  91  92  93  94  95  96  97 100 100]]


### boolean indexing

In [127]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [128]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [129]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2<2) | (arr2>4)])    

[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [53]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[ 33 100 100]
[[ 36  34 100]
 [100 100 100]
 [100 100 100]]


In [ ]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

### dimension inference

In [133]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)

(4, 4)


# 7. Sort Arrays

In [134]:
arr = np.random.rand(5,5)

### sort an array along a specified axis

In [ ]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

In [ ]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

In [135]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.35204183 0.51761868 0.63277886 0.71519128 0.87311902]
 [0.06546154 0.16788844 0.34941493 0.82620513 0.98747832]
 [0.00535329 0.02755138 0.19940777 0.88694465 0.91131813]
 [0.05608301 0.06756083 0.24182762 0.47387186 0.81733492]
 [0.25584293 0.38151211 0.41679514 0.50942926 0.80738444]]


In [ ]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

# 8. Copy Arrays

In [136]:
arr = np.array([1,2,3])

In [137]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

# 9. Manipulate Arrays

In [142]:
arr = np.random.rand(3,4)

### transpose an array

In [138]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[1 2 3]
[1 2 3]
[1 2 3]


### transpose of a high dimensional array with specified order of axes

In [139]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


### swap axes

In [140]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [143]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.81103914, 0.68618686, 0.99261363, 0.40518518, 0.19017372,
        0.48817449],
       [0.50236965, 0.40335482, 0.18109542, 0.0480298 , 0.60469135,
        0.26591121]])

In [ ]:
# change the shape of an array in place
arr.resize((2,6))

### flatten an array

In [145]:
# return a copy
arr.flatten()    

array([0.81103914, 0.68618686, 0.99261363, 0.40518518, 0.19017372,
       0.48817449, 0.50236965, 0.40335482, 0.18109542, 0.0480298 ,
       0.60469135, 0.26591121])

In [146]:
# return a view
# change any element in the view will also change the initial array
arr.ravel()      

array([0.81103914, 0.68618686, 0.99261363, 0.40518518, 0.19017372,
       0.48817449, 0.50236965, 0.40335482, 0.18109542, 0.0480298 ,
       0.60469135, 0.26591121])

### append elements to an array

In [147]:
arr = np.array([1,2,3])

In [ ]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

In [ ]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

### insert elements into an array

In [ ]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

In [ ]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

### delete elements from an array

In [ ]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

In [61]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[1 2 3 4]
[1 2 3 4 5 6]
[100   1   2   3]
[1 2 3 1 2 3]
[2 3]
[2]


# 10. Combine & Split Arrays

In [62]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### np.concatenate((a, b), axis=0)

In [63]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

### np.vstack((a, b)) 
### np.r_[a, b]

In [64]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

### np.hstack((a, b))
### np.c_[a, b]

In [ ]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

In [ ]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

### split the array 

In [150]:
arr = np.random.rand(6,6)

In [152]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.37251939, 0.33997017, 0.81257008, 0.52820553, 0.55382711,
        0.11720684],
       [0.78460482, 0.43458619, 0.07722273, 0.18181153, 0.52101088,
        0.47933417],
       [0.31354249, 0.09966921, 0.59655266, 0.24816989, 0.60434016,
        0.30511365]]), array([[0.89730494, 0.58201533, 0.71249243, 0.68361547, 0.9466209 ,
        0.91323126],
       [0.05125491, 0.38031548, 0.56385654, 0.13257374, 0.57513529,
        0.32256775],
       [0.98392756, 0.57566582, 0.62972763, 0.40101228, 0.74463006,
        0.40118593]])]


In [151]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.37251939, 0.33997017, 0.81257008],
       [0.78460482, 0.43458619, 0.07722273],
       [0.31354249, 0.09966921, 0.59655266],
       [0.89730494, 0.58201533, 0.71249243],
       [0.05125491, 0.38031548, 0.56385654],
       [0.98392756, 0.57566582, 0.62972763]]), array([[0.52820553, 0.55382711, 0.11720684],
       [0.18181153, 0.52101088, 0.47933417],
       [0.24816989, 0.60434016, 0.30511365],
       [0.68361547, 0.9466209 , 0.91323126],
       [0.13257374, 0.57513529, 0.32256775],
       [0.40101228, 0.74463006, 0.40118593]])]


# 11. Set Operations

### select the unique elements from an array

In [66]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


### compute the intersection & union of two arrays

In [153]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

[3 4 5]


In [ ]:
# intersection
print(np.intersect1d(arr1, arr2))

In [154]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### compute whether each element of an array is contained in another

In [68]:
print(np.in1d(arr1, arr2))

[False False  True  True  True]


### compute elements in an array that are not in another

In [69]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute elements in either of two arrays, but not both

In [155]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


# 12. Linear Algebra

In [156]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [157]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[0.30828825 1.31341456 1.71359169 1.05014023 1.51707868]
 [0.4003542  1.15768971 1.68948314 1.03610757 1.16733359]
 [0.61073505 1.33554797 2.32210555 1.46130201 1.55075334]
 [0.48407188 1.50579216 2.25788865 1.27427842 1.7504286 ]
 [0.35585457 1.05682391 1.9038537  0.84436397 1.39865383]]
[[0.30828825 1.31341456 1.71359169 1.05014023 1.51707868]
 [0.4003542  1.15768971 1.68948314 1.03610757 1.16733359]
 [0.61073505 1.33554797 2.32210555 1.46130201 1.55075334]
 [0.48407188 1.50579216 2.25788865 1.27427842 1.7504286 ]
 [0.35585457 1.05682391 1.9038537  0.84436397 1.39865383]]
[[0.30828825 1.31341456 1.71359169 1.05014023 1.51707868]
 [0.4003542  1.15768971 1.68948314 1.03610757 1.16733359]
 [0.61073505 1.33554797 2.32210555 1.46130201 1.55075334]
 [0.48407188 1.50579216 2.25788865 1.27427842 1.7504286 ]
 [0.35585457 1.05682391 1.9038537  0.84436397 1.39865383]]


### QR factorization 

In [158]:
arr = np.random.rand(5,5)

q, r = np.linalg.qr(arr)
print(q)
print(r)

[[-0.63906042  0.19015204  0.71457819  0.20654786 -0.04647552]
 [-0.38857178 -0.80392412 -0.04733022 -0.20933085  0.395801  ]
 [-0.37513121 -0.14990226 -0.50958107  0.65291582 -0.38837346]
 [-0.28784082 -0.02013848 -0.10579889 -0.66022051 -0.68531568]
 [-0.46587335  0.54283697 -0.4650501  -0.22655769  0.46977661]]
[[-1.3910887  -1.31347776 -1.08849098 -0.85132662 -1.36971554]
 [ 0.         -0.57884872 -0.00912357  0.30797563 -0.23811881]
 [ 0.          0.         -0.83903466  0.09083423 -0.04021102]
 [ 0.          0.          0.          0.18969792  0.29783318]
 [ 0.          0.          0.          0.         -0.37829727]]


### singular value decomposition (SVD)

In [159]:
arr = np.random.rand(5,5)

u, s, v = np.linalg.svd(arr)
print(u)
print(s)
print(v)

[[-4.15860796e-01 -7.62273017e-01  1.62497207e-01 -4.42705830e-01
   1.53641958e-01]
 [-5.19206677e-01 -2.45541728e-01 -2.25166251e-01  7.09995183e-01
  -3.39618440e-01]
 [-3.74555489e-01  2.43673587e-01 -5.11109651e-01 -5.14470321e-04
   7.34232952e-01]
 [-3.99501173e-01  3.26581714e-01  7.98663308e-01  1.90754361e-01
   2.43911645e-01]
 [-5.07534454e-01  4.38881162e-01 -1.54268148e-01 -5.13352605e-01
  -5.12310984e-01]]
[2.86877045 0.68622304 0.29830764 0.24950606 0.0751793 ]
[[-0.40674202 -0.46302528 -0.51600993 -0.23528951 -0.54638917]
 [ 0.21926793  0.06959774 -0.20586935 -0.88337611  0.35262187]
 [ 0.87972556 -0.15704524 -0.13885686  0.07031881 -0.42094391]
 [-0.05840109  0.85422117 -0.42214275  0.03303967 -0.29597193]
 [-0.09568052  0.16250148  0.70275589 -0.3978054  -0.55885914]]


### compute eigen values

In [161]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

[ 1.97614398  0.90598748 -0.49802514  0.04287253 -0.14578635]


### eigen value decomposition

In [75]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

[ 2.33630197+0.j          0.33523958+0.35026881j  0.33523958-0.35026881j
  0.0841337 +0.j         -0.31131644+0.j        ]
[[-0.44279031+0.j          0.07593363+0.1747749j   0.07593363-0.1747749j
   0.59332907+0.j          0.65189823+0.j        ]
 [-0.46637434+0.j         -0.33157173-0.02492161j -0.33157173+0.02492161j
  -0.08844859+0.j         -0.62964299+0.j        ]
 [-0.4870652 +0.j          0.66384086+0.j          0.66384086-0.j
  -0.0088532 +0.j         -0.12454342+0.j        ]
 [-0.4519609 +0.j         -0.02686292-0.49518962j -0.02686292+0.49518962j
   0.35038848+0.j          0.33394839+0.j        ]
 [-0.38069745+0.j          0.1371586 +0.38431156j  0.1371586 -0.38431156j
  -0.71922666+0.j          0.22703703+0.j        ]]
[ 2.33630197+0.j          0.33523958+0.35026881j  0.33523958-0.35026881j
  0.0841337 +0.j         -0.31131644+0.j        ]


### compute the trace & determinant

In [163]:
# notice this is not a function in linalg!!!
print(np.trace(arr))    

2.281192488960085


In [162]:
print(np.linalg.det(arr))

0.0055729866028321265


### calculate the inverse/psedo-inverse of a matrix

In [164]:
arr = np.random.rand(5,5)

In [165]:
# compute the inverse of a matrix
print(np.linalg.inv(arr))

[[ -0.97830338  -2.20981754   0.95894578   0.62679115   0.92804423]
 [  0.43816449  -5.15179288  -1.32833847   3.36089528   1.17453396]
 [  0.8170133   -9.66910037  -1.15591468   8.40749557  -2.22542588]
 [  0.64076525   4.50395115   0.98453279  -3.52284304  -0.28373188]
 [ -0.85079622  15.75675509   1.77878975 -10.5556761    0.61987089]]


In [166]:
# compute the psudo-inverse of a matrix
print(np.linalg.pinv(arr))

[[ -0.97830338  -2.20981754   0.95894578   0.62679115   0.92804423]
 [  0.43816449  -5.15179288  -1.32833847   3.36089528   1.17453396]
 [  0.8170133   -9.66910037  -1.15591468   8.40749557  -2.22542588]
 [  0.64076525   4.50395115   0.98453279  -3.52284304  -0.28373188]
 [ -0.85079622  15.75675509   1.77878975 -10.5556761    0.61987089]]


### solve a linear system

In [167]:
# solve a linear system in closed form
y = [1,2,3,4,5]
print(np.linalg.solve(arr, y))

[ 4.62628463  5.4658142   0.51392141 -2.90776561 -3.12426672]


In [168]:
# calculate the least-squares solution of a linear system
y = [1,2,3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[ 4.62628463  5.4658142   0.51392141 -2.90776561 -3.12426672]
[]
5
[2.57240739 0.9105451  0.59528048 0.340292   0.04063458]


C:\Users\ewang\AppData\Local\Continuum\miniconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until
